//! 基于 clipboard-rs 的剪贴板读写，以及图片处理（缩略图/哈希）。
//!
//! 注意：ClipboardContext 不跨线程传递——所有函数内部各自 new()，
//! 由调用方（轮询线程 / 命令处理）按需创建。

use std::hash::{Hash, Hasher};
use std::io::Cursor;
use std::path::PathBuf;

use base64::{engine::general_purpose::STANDARD, Engine as _};
use clipboard_rs::common::{RustImage, RustImageData};
use clipboard_rs::{Clipboard, ClipboardContext, ContentFormat};
use tauri::{AppHandle, Manager};

/// 缩略图最长边上限。
const THUMB_MAX: u32 = 240;

/// 一次读取到的剪贴板内容（按 图片 > 文件 > 文本 优先级）。
pub enum ClipRead {
    Text(String),
    Files(Vec<String>),
    /// 完整 PNG 字节。
    Image(Vec<u8>),
}

/// 读取系统剪贴板当前内容。优先级：图片 > 文件 > 文本。空内容返回 None。
pub fn read_clipboard() -> Option<ClipRead> {
    let ctx = ClipboardContext::new().ok()?;

    if ctx.has(ContentFormat::Image) {
        if let Ok(img) = ctx.get_image() {
            if let Ok(buf) = img.to_png() {
                let png = buf.get_bytes().to_vec();
                if !png.is_empty() {
                    return Some(ClipRead::Image(png));
                }
            }
        }
    }

    if ctx.has(ContentFormat::Files) {
        if let Ok(files) = ctx.get_files() {
            let files: Vec<String> = files
                .iter()
                .map(|f| normalize_file_path(f))
                .filter(|p| !p.is_empty())
                .collect();
            if !files.is_empty() {
                return Some(ClipRead::Files(files));
            }
        }
    }

    if ctx.has(ContentFormat::Text) {
        if let Ok(t) = ctx.get_text() {
            if !t.is_empty() {
                return Some(ClipRead::Text(t));
            }
        }
    }

    None
}

/// 检测当前系统剪贴板是否被标记为密码/敏感/自动生成内容
/// （org.nspasteboard.ConcealedType / TransientType / AutoGeneratedType）。
/// 命中任一即视为应忽略；读取失败时保守返回 false（不忽略）。
pub fn is_concealed() -> bool {
    const CONCEALED_TYPES: [&str; 3] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];
    let Ok(ctx) = ClipboardContext::new() else {
        return false;
    };
    CONCEALED_TYPES
        .iter()
        .any(|t| ctx.has(ContentFormat::Other((*t).to_string())))
}

/// 把文本写回系统剪贴板。
pub fn write_text(text: &str) -> bool {
    match ClipboardContext::new() {
        Ok(ctx) => ctx.set_text(text.to_string()).is_ok(),
        Err(_) => false,
    }
}

/// 把文件路径列表写回系统剪贴板。
pub fn write_files(files: &[String]) -> bool {
    match ClipboardContext::new() {
        Ok(ctx) => ctx.set_files(files.to_vec()).is_ok(),
        Err(_) => false,
    }
}

/// 从磁盘 PNG 文件读取并写回系统剪贴板（图片）。
pub fn write_image_file(path: &str) -> bool {
    let Ok(bytes) = std::fs::read(path) else {
        return false;
    };
    let Ok(img) = RustImageData::from_bytes(&bytes) else {
        return false;
    };
    match ClipboardContext::new() {
        Ok(ctx) => ctx.set_image(img).is_ok(),
        Err(_) => false,
    }
}

/// images 目录： app_data_dir()/images
fn images_dir(app: &AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_data_dir().ok()?;
    let d = dir.join("images");
    let _ = std::fs::create_dir_all(&d);
    Some(d)
}

/// 把完整 PNG 落盘到 images/<id>.png，返回绝对路径字符串。
pub fn save_image_png(app: &AppHandle, id: u64, png: &[u8]) -> Option<String> {
    let dir = images_dir(app)?;
    let path = dir.join(format!("{id}.png"));
    std::fs::write(&path, png).ok()?;
    Some(path.to_string_lossy().to_string())
}

/// 解码 PNG，计算稳定的像素内容哈希（用于去重），并生成缩略图 base64 data URL。
///
/// 哈希基于解码后的 RGBA 像素而非 PNG 字节，从而在「写回剪贴板→再次读出」
/// 的往返中保持稳定，避免重复记录。
pub fn process_image(png: &[u8]) -> Option<(u64, String)> {
    let img = image::load_from_memory(png).ok()?;

    let rgba = img.to_rgba8();
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    img.width().hash(&mut hasher);
    img.height().hash(&mut hasher);
    rgba.as_raw().hash(&mut hasher);
    let hash = hasher.finish();

    // thumbnail 保持纵横比，缩放到最长边 <= THUMB_MAX。
    let thumb = img.thumbnail(THUMB_MAX, THUMB_MAX);
    let mut buf = Cursor::new(Vec::new());
    thumb.write_to(&mut buf, image::ImageFormat::Png).ok()?;
    let b64 = STANDARD.encode(buf.into_inner());

    Some((hash, format!("data:image/png;base64,{b64}")))
}

/// 规范化文件路径：去掉 file:// 前缀并做百分号解码。
pub fn normalize_file_path(p: &str) -> String {
    let s = p.trim();
    let s = s.strip_prefix("file://").unwrap_or(s);
    percent_decode(s)
}

fn hex_val(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(h), Some(l)) = (hex_val(bytes[i + 1]), hex_val(bytes[i + 2])) {
                out.push(h * 16 + l);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).to_string()
}
